@GoalTracker.API_HostAddress = https://localhost:7124


###

GET {{GoalTracker.API_HostAddress}}/api/goals

###

GET {{GoalTracker.API_HostAddress}}/api/goals/5

###

POST {{GoalTracker.API_HostAddress}}/api/goals
Content-Type: application/json

{
 
    "title": "Learn sql Fundamentals2",
    "description": "Master sql web development",
    "createdDate": "2024-12-29T12:32:24.2476361",
    "targetDate": null,
    "status": 3,
    "priority": 8
    
}

###

@id=3
DELETE {{GoalTracker.API_HostAddress}}/api/goals/{{id}}

###

PATCH {{GoalTracker.API_HostAddress}}/api/goals/5
Content-Type: application/json

{
  "title": "Learn edit sql Fundamentals Edited",
    "description": "Master edit sql web development Edited",
    "status": 4,
    "priority": 4
}

###

POST {{GoalTracker.API_HostAddress}}/api/goals/8/WorkItems
Content-Type: application/json

{
        "Title": "Design User Interface 2",
        "description": "Create Blazor components for goal tracking  2",
       
        "status": 3
        
       }

###

@GoalId=0
POST {{GoalTracker.API_HostAddress}}/api/goal/3/WorkItems

###

###

GET {{GoalTracker.API_HostAddress}}/api/goals/5/WorkItems

###

GET {{GoalTracker.API_HostAddress}}/api/goals/{{goalId}}/WorkItems

###

@workItemId=0
GET {{GoalTracker.API_HostAddress}}/api/goals/50/workitems/70

###

DELETE {{GoalTracker.API_HostAddress}}/api/goals/5/workitems

###

POST {{GoalTracker.API_HostAddress}}/api/goals/5/WorkItems
Content-Type: application/json

{
   "Title": "Design User Interface New",
        "description": "Create Blazor components for goal tracking  2",
       
        "status": 3
}

###
