@GoalTracker.API_HostAddress = https://localhost:7124
@port =5028
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzZmEzNDRhYi1lMzY0LTRmYzEtYWY2NC1kMTc1NDFlMzdkMWYiLCJlbWFpbCI6IkFETUlOQEdNQUlMLkNPTSIsInVuaXF1ZV9uYW1lIjoiQURNSU5AR01BSUwuQ09NIiwianRpIjoiYzc5NmVkZTItMzRjNi00NjkxLTgwZDYtM2FmZmNjMTgzYTZiIiwibmJmIjoxNzQ5NDY5MzIxLCJleHAiOjE3NDk0NzI5MjEsImlhdCI6MTc0OTQ2OTMyMSwiaXNzIjoiR29hbFRyYWNrZXJBcHAiLCJhdWQiOiJHb2FsVHJhY2tlclVzZXJzIn0.Ej7j1BgAx0mUp5SgrAt5TgDVH2apmz_5fj4InKT5728
###
// "password": "P@ssw0rd1"
POST {{GoalTracker.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
 "email":"ADMIN@GMAIL.COM",
 "password":"Password1!"
}
###
GET {{GoalTracker.API_HostAddress}}/api/goals?searchPharse=&pageNumber=1&pageSize=10&sortBy=Title&sortDirection=1
Content-Type: application/json
Authorization: Bearer {{token}}

### Register a new user
POST {{GoalTracker.API_HostAddress}}/api/Register
Content-Type: application/json

{
  "userName": "test1user",
  "email": "test1@example.com",
  "password": "Password123!"
}



###

POST {{GoalTracker.API_HostAddress}}/api/goals
Content-Type: application/json

{
 
    "title": "Learn sql Fundamentals2",
    "description": "Master sql web development",
    "createdDate": "2024-12-29T12:32:24.2476361",
    "targetDate": null,
    "status": 3,
    "priority": 8
    
}

###

@id=4
DELETE {{GoalTracker.API_HostAddress}}/api/goals/{{id}}

###

PATCH {{GoalTracker.API_HostAddress}}/api/goals/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Learn edit sql Fundamentals Updated",
    "description": "Master edit sql web development Edited",
    "status": 4,
    "priority": 4
}

###

POST {{GoalTracker.API_HostAddress}}/api/goals/8/WorkItems
Content-Type: application/json

{
        "Title": "Design User Interface 2",
        "description": "Create Blazor components for goal tracking  2",
       
        "status": 3
        
       }

###

@GoalId=0
POST {{GoalTracker.API_HostAddress}}/api/goal/3/WorkItems

###

###

GET {{GoalTracker.API_HostAddress}}/api/goals/5/WorkItems

###

GET {{GoalTracker.API_HostAddress}}/api/goals/{{goalId}}/WorkItems

###

@workItemId=0
GET {{GoalTracker.API_HostAddress}}/api/goals/50/workitems/70

###

DELETE {{GoalTracker.API_HostAddress}}/api/goals/5/workitems

###

POST {{GoalTracker.API_HostAddress}}/api/goals/5/WorkItems
Content-Type: application/json

{
   "Title": "Design User Interface New",
        "description": "Create Blazor components for goal tracking  2",
       
        "status": 3
}

###
POST {{GoalTracker.API_HostAddress}}/api/register
Content-Type: application/json
{

"email":"haifa@test.com",
"password":"Password1!"
}

###

POST {{GoalTracker.API_HostAddress}}/login
Content-Type: application/json
{

"email":"testuser@test.com",
"password":"Password1!"
}
###
GET {{GoalTracker.API_HostAddress}}/api/goals?SearchPharse=blazore&pageSize=5&pageNumber=1&sortBy=Title
Content-Type: application/json


###

POST {{GoalTracker.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "UserEmail":"testuser@test.com",
    "RoleName":"Viewer"
  
}

###

DELETE {{GoalTracker.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "UserEmail":"testuser@test.com",
    "RoleName":"Viewer"
  
}

###

GET {{GoalTracker.API_HostAddress}}/api/goals{
   "searchPharse"": "",
            "pageNumber": 1,     // Ensuring this is at least 1
            "pageSize": 10,      // Using one of the allowed values (5, 10, 15, 30)
            "sortBy": "Title",
            "sortDirection": 1
}

###
GET {{GoalTracker.API_HostAddress}}/api/goals?searchPharse=&pageNumber=1&pageSize=10&sortBy=Title&sortDirection=1
###

GET {{GoalTracker.API_HostAddress}}/api/goals?searchPharse=&pageNumber=1&pageSize=10&sortBy=Title&sortDirection=1

###

### Test 1: Update Goal with Basic Properties Only
PUT {{GoalTracker.API_HostAddress}}/api/goals/4
Content-Type: application/json

Authorization: Bearer {{token}}

{
  "id": 4,
  "title": "Updated Goal Title - Basic Update",
  "description": "This goal has been updated with basic properties only",
  "targetDate": "2024-12-31T23:59:59Z",
  "status": 1,
  "priority": 2
}
